import type { FullResult, Suite } from "@playwright/test/reporter"

/**
 * Report types that can be generated by the Telegram reporter
 * - simple: Just pass/fail status
 * - summary: Status + total/passed/failed/skipped counts + duration
 * - detailed: All tests with individual results, error messages for failures
 */
export type ReportType = "simple" | "summary" | "detailed"

/**
 * When to send the Telegram report
 * - always: Send report on every test run (default)
 * - failure: Only send when tests fail
 * - success: Only send when all tests pass
 */
export type SendOn = "always" | "failure" | "success"

/**
 * Configuration options for the Telegram reporter
 */
export interface TelegramReporterOptions {
  /**
   * Telegram Bot Token (get it from @BotFather)
   */
  botToken: string

  /**
   * Telegram Chat ID where messages will be sent
   */
  chatId: string

  /**
   * Type of report to generate (default: 'detailed')
   */
  reportType?: ReportType

  /**
   * Custom formatter function for generating the report text
   * If provided, this will be used instead of the built-in report types
   */
  customFormatter?: (result: FullResult, suite: Suite) => string

  /**
   * When to send the report (default: 'always')
   */
  sendOn?: SendOn

  /**
   * Format template for test names in detailed reports
   * Available variables: {BROWSER}, {FILENAME}, {GROUP}, {TEST}, {TIME}
   * Default: '{GROUP} › {TEST} ({TIME})'
   *
   * Examples:
   * - '{GROUP} › {TEST} ({TIME})' - "Example Tests › has heading (0.58s)"
   * - '{BROWSER} | {TEST} ({TIME})' - "chromium | has heading (0.58s)"
   * - '{TEST}' - "has heading"
   */
  testFormat?: string

  /**
   * Custom title for the report message (first line)
   * Can be a string or a function that receives test pass status
   * Default: '✅ Playwright Test Results' or '❌ Playwright Test Results'
   *
   * Examples:
   * - 'My Custom Tests'
   * - (passed) => passed ? '✅ All Good!' : '❌ Tests Failed'
   */
  title?: string | ((passed: boolean) => string)
}
