import type { FullResult, Suite } from "@playwright/test/reporter"

/**
 * Report types that can be generated by the Telegram reporter
 * - simple: Just pass/fail status
 * - summary: Status + total/passed/failed/skipped counts + duration
 * - detailed: All tests with individual results, error messages for failures
 */
export type ReportType = "simple" | "summary" | "detailed"

/**
 * When to send the Telegram report
 * - always: Send report on every test run (default)
 * - failure: Only send when tests fail
 * - success: Only send when all tests pass
 */
export type SendOn = "always" | "failure" | "success"

/**
 * Configuration options for the Telegram reporter
 */
export interface TelegramReporterOptions {
  /**
   * Telegram Bot Token (get it from @BotFather)
   */
  botToken: string

  /**
   * Telegram Chat ID where messages will be sent
   */
  chatId: string

  /**
   * Type of report to generate (default: 'summary')
   */
  reportType?: ReportType

  /**
   * Custom formatter function for generating the report text
   * If provided, this will be used instead of the built-in report types
   */
  customFormatter?: (result: FullResult, suite: Suite) => string

  /**
   * When to send the report (default: 'always')
   */
  sendOn?: SendOn
}
